os:
  - linux
language: generic
sudo: required
dist: trusty
script:
  # Install wkhtmltopdf
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin
  # Build and test
  - eval "$(curl -sL https://swift.vapor.sh/ci-3.1)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
